[languages.py]
compile = "python3 -mpy_compile {path}"
execute = "python3 {path}"
bundle = "false"
list_attributes = "sed -n 's/^# verify-helper: //p' {path}"
list_dependencies = "sed -n 's/^from \\(.*\\) import .*# path: \\(.*\\)$/\\2\\1.py/p' {path}"